### ISSUE TITLE
saw .pug files but there wasn't associated pug images

### ISSUE THREAD

**Issue by Asymons** [cybervinit/picky-appserver#1]
i want cute dogs

**Comment by robertsimoes** [comment]
I double tag this issue. Looking to put out some funding for this issue on https://gitcoin.co/

**Comment by cybervinit** [comment]
As per the request, the fix has been pushed, you can now access the pug image [here](https://github.com/cybervinit/picky-appserver/blob/db-setup/public/images/pug_pic.jpg). More to come upon funding received at 155M7TvSWAGSWAGSWAGSWAGSWAGeNafCfd
